package com.dossier.backend.conversation;

import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * TDD 5.1 — DynamicSuggestion entity
 * Follow-up prompt suggestions dynamically generated by the AI model via Tool Use at the end of assistant messages
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@Entity
@Table(name = "dynamic_suggestions")
public class DynamicSuggestion {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "message_id", nullable = false)
    private Message message;

    @Column(name = "text", nullable = false, length = 500)
    private String text;

    @Column(name = "sort_order", nullable = false)
    private Integer sortOrder;
}
